In [5]:
# ASSIGNMENT
# input=s2b3c6
# output=ssbbbcccccc
a=input()
out=""
for i in a:
    if i.isalpha():
        alp=i
    else:
        dig=int(i)
        out=out+alp*(dig)
print(out)

ẞ2g4f6
ẞẞggggffffff


In [6]:
import numpy as np
k=np.arange(10)
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
k=np.arange(10)
a=k.reshape(5,2)
b=k.dtype
print(b)
print(a)

int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [8]:
k=np.arange(10)
print(k.ndim)

1


In [9]:
kk=np.full((5,2),4)
print(kk)

[[4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]


In [10]:
rd=np.random.rand(5)
print(rd)
# we will get 5 no,s randomly
# only +ve no's

[0.36587369 0.36996983 0.03780866 0.26221188 0.40417844]


In [11]:
rd=np.random.randn(5)
print(rd)
# combination of +ve & -ve

[-0.85221942 -0.02291952 -0.06825319  0.82224313  0.62947253]


In [12]:
ktr=np.arange(12).reshape(3,4)
print(ktr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
ktr=np.arange(12).reshape(6,2)
print(ktr)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [14]:
ktr=np.arange(12).reshape(3,4)
print(ktr.min())
print(ktr.max())
print(ktr.std())

0
11
3.452052529534663


In [15]:
ktr=np.arange(12).reshape(6,2)
a=np.max(ktr,axis=1)
print(a)

[ 1  3  5  7  9 11]


In [16]:
ktr=np.arange(12).reshape(6,2)
a=np.min(ktr,axis=0)
print(a)

[0 1]


In [17]:
ln=np.linspace(1,100,5)
print(ln)

[  1.    25.75  50.5   75.25 100.  ]


# PANDAS
- pandas as data sets 
- series--->1D
- dataframes--->2D
- datasets

In [18]:
# pandas is lib from
import pandas as pd
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_versio

In [19]:
a=pd.Series([1,2,3,4,5])# S is capital
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [20]:
slt=np.arange(5,10,1)
b=pd.Series(slt)
print(b)
print(b.values)
print(b.index)

0    5
1    6
2    7
3    8
4    9
dtype: int64
[5 6 7 8 9]
RangeIndex(start=0, stop=5, step=1)


In [21]:
a=pd.Series([1,2,3,4,5])
print(a.min())
print(a.max())

1
5


In [22]:
slt=np.arange(5,10,1)
c=pd.Series(slt,index=["a","b","c","d","e"])
print(c)

a    5
b    6
c    7
d    8
e    9
dtype: int64


In [23]:
print(c[4]==c["e"])

True


In [24]:
print(c[0]==c["a"])

True


In [25]:
print(c[c>6])
print(c[c>7])
print(c[4])

c    7
d    8
e    9
dtype: int64
d    8
e    9
dtype: int64
9


- data frames--->2d array in pandas
- tabular data rows 7 coloumns

In [26]:
ria={"name":["harsha","joel","mani","raja","vijay"],
     "dob":["2003","2002","2001","2004","2000"],
     "branch":["cse","it","ai","ds","ece"]
    }
df=pd.DataFrame(ria)
(df)

name   dob branch
0  harsha  2003    cse
1    joel  2002     it
2    mani  2001     ai
3    raja  2004     ds
4   vijay  2000    ece

In [27]:
ria={"name":["harsha","joel","mani","raja","vijay"],
     "dob":["2003","2002","2001","2004","2000"],
     "branch":["cse","it","ai","ds","ece"]
    }
df=pd.DataFrame(ria)
(df.head(3))

name   dob branch
0  harsha  2003    cse
1    joel  2002     it
2    mani  2001     ai

In [28]:
ria={"name":["harsha","joel","mani","raja","vijay"],
     "dob":["2003","2002","2001","2004","2000"],
     "branch":["cse","it","ai","ds","ece"]
    }
df=pd.DataFrame(ria)
(df.tail(3))

name   dob branch
2   mani  2001     ai
3   raja  2004     ds
4  vijay  2000    ece

In [29]:
ria={"name":["harsha","joel","mani","raja","vijay"],
     "dob":["2003","2002","2001","2004","2000"],
     "branch":["cse","it","ai","ds","ece"]
    }
df=pd.DataFrame(ria)
df1=pd.DataFrame(df,columns=["name","dob","branch","marks"])
(df1)

name   dob branch  marks
0  harsha  2003    cse    NaN
1    joel  2002     it    NaN
2    mani  2001     ai    NaN
3    raja  2004     ds    NaN
4   vijay  2000    ece    NaN

In [30]:
df1.isnull()

name    dob  branch  marks
0  False  False   False   True
1  False  False   False   True
2  False  False   False   True
3  False  False   False   True
4  False  False   False   True

In [31]:
df1["name"]

0    harsha
1      joel
2      mani
3      raja
4     vijay
Name: name, dtype: object

In [32]:
df1["dob"]

0    2003
1    2002
2    2001
3    2004
4    2000
Name: dob, dtype: object

In [33]:
df1["marks"]=[12,13,14,15,16]#np.random.rand(5)
df1

name   dob branch  marks
0  harsha  2003    cse     12
1    joel  2002     it     13
2    mani  2001     ai     14
3    raja  2004     ds     15
4   vijay  2000    ece     16

In [34]:
df1.drop(4)

name   dob branch  marks
0  harsha  2003    cse     12
1    joel  2002     it     13
2    mani  2001     ai     14
3    raja  2004     ds     15

In [35]:
ls#ksrcs.csv to check

Alarms/
Android/
Audiobooks/
ColorOS/
DCIM/
Data-Regstration.pdf
Documents/
Download/
Fonts/
JioSwitch/
Movies/
Music/
Notifications/
PDF'S/
PicsArt/
Pictures/
Podcasts/
Python Programming's Meeting Attendees.xls
Subtitles/
Untitled.ipynb
VidMate/
__pycache__/
apssdc/
iLovePDF/
inShare/
ksrcs.csv
ksrdata.pdf
oplus_log/
python/


In [36]:
#read_csv()
#read_json()
#read_excel()

In [38]:
data=pd.read_csv("ksrcs.csv")
data

Roll-No                Name  Python   C  Java  DS  OS  DBMS  Marks  \
0    20JR1A0590            M.Sushma       4  97     4  88  41    52    286   
1    20JR1A0591     Nagumothu Navya      80  77    49  45  70     0    321   
2    20JR1A0592    N.Lakshmi Vasavi      43  69    21   8  93    91    325   
3    20JR1A0593      Sushma Namburi      34  72    97  42  33    71    349   
4    20JR1A0594  N.lakshmi Chandana      93  95    14  10  73    20    305   
..          ...                 ...     ...  ..   ...  ..  ..   ...    ...   
156  20JR1A4442               VIVEK      66  87     2  79  92    16    342   
157  20JR1AO5J2     Charan Siva Sai      73  58    33  56  56    19    295   
158  20jr1A0518              anusha      33  61    26  53  29    18    220   
159  20jr1a0552                 Abc      68  26    18  20  24    70    226   
160  20jr1ao5d8               hello      16  94    98   9  58    10    285   

    Grade  
0    Pass  
1    Pass  
2    Pass  
3    Pass  
4    Pass  
..    ...  
156  Pass  
157  Pass  
158  Pass  
159  Pass  
160  Pass  

[161 rows x 10 columns]

In [39]:
data.head(10)

Roll-No                Name  Python    C  Java  DS  OS  DBMS  Marks  \
0  20JR1A0590            M.Sushma       4   97     4  88  41    52    286   
1  20JR1A0591     Nagumothu Navya      80   77    49  45  70     0    321   
2  20JR1A0592    N.Lakshmi Vasavi      43   69    21   8  93    91    325   
3  20JR1A0593      Sushma Namburi      34   72    97  42  33    71    349   
4  20JR1A0594  N.lakshmi Chandana      93   95    14  10  73    20    305   
5  20JR1A0595              swapna      70   22    37  41   1    16    187   
6  20JR1A0596        GSP SRIKANTH      95   65     2  86  91    66    405   
7  20JR1A0597             prakash      72   42    54  45  98    84    395   
8  20JR1A0598       harsha Ravuri      86   23    82  27  77     4    299   
9  20JR1A05A2     K Nagendra Babu      25  100    72  56   6    63    322   

  Grade  
0  Pass  
1  Pass  
2  Pass  
3  Pass  
4  Pass  
5  Fail  
6  Pass  
7  Pass  
8  Pass  
9  Pass

In [40]:
data.head(5)

Roll-No                Name  Python   C  Java  DS  OS  DBMS  Marks Grade
0  20JR1A0590            M.Sushma       4  97     4  88  41    52    286  Pass
1  20JR1A0591     Nagumothu Navya      80  77    49  45  70     0    321  Pass
2  20JR1A0592    N.Lakshmi Vasavi      43  69    21   8  93    91    325  Pass
3  20JR1A0593      Sushma Namburi      34  72    97  42  33    71    349  Pass
4  20JR1A0594  N.lakshmi Chandana      93  95    14  10  73    20    305  Pass

In [41]:
data.tail(10)

Roll-No                          Name  Python   C  Java  DS  OS  DBMS  \
151  20JR1A4362            SK.B.SHOHEB AKTHAR      81  95    27  27  34    88   
152  20JR1A4363                        MUNEER      46  57    55   9  70    50   
153  20JR1A4364  Naga Sai Durgesh Singamsetty      65  62     9  54  46    67   
154  20JR1A4431           Sakhamuri. Lathasri      65  89    57  32  82    80   
155  20JR1A4435                      Rushitha      17  61    83  12   3    67   
156  20JR1A4442                         VIVEK      66  87     2  79  92    16   
157  20JR1AO5J2               Charan Siva Sai      73  58    33  56  56    19   
158  20jr1A0518                        anusha      33  61    26  53  29    18   
159  20jr1a0552                           Abc      68  26    18  20  24    70   
160  20jr1ao5d8                         hello      16  94    98   9  58    10   

     Marks Grade  
151    352  Pass  
152    287  Pass  
153    303  Pass  
154    405  Pass  
155    243  Pass  
156    342  Pass  
157    295  Pass  
158    220  Pass  
159    226  Pass  
160    285  Pass

In [42]:
data.tail(5)

Roll-No             Name  Python   C  Java  DS  OS  DBMS  Marks Grade
156  20JR1A4442            VIVEK      66  87     2  79  92    16    342  Pass
157  20JR1AO5J2  Charan Siva Sai      73  58    33  56  56    19    295  Pass
158  20jr1A0518           anusha      33  61    26  53  29    18    220  Pass
159  20jr1a0552              Abc      68  26    18  20  24    70    226  Pass
160  20jr1ao5d8            hello      16  94    98   9  58    10    285  Pass

In [43]:
data.min()

Roll-No    20JR1A0590
Python              0
C                   0
Java                0
DS                  1
OS                  0
DBMS                0
Marks             107
Grade            Fail
dtype: object

In [44]:
data.max()

Roll-No    20jr1ao5d8
Python             99
C                 100
Java              100
DS                100
OS                100
DBMS              100
Marks             441
Grade            Pass
dtype: object

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Roll-No  161 non-null    object
 1   Name     154 non-null    object
 2   Python   161 non-null    int64 
 3   C        161 non-null    int64 
 4   Java     161 non-null    int64 
 5   DS       161 non-null    int64 
 6   OS       161 non-null    int64 
 7   DBMS     161 non-null    int64 
 8   Marks    161 non-null    int64 
 9   Grade    161 non-null    object
dtypes: int64(7), object(3)
memory usage: 12.7+ KB


In [46]:
data.describe()

Python           C        Java          DS          OS        DBMS  \
count  161.000000  161.000000  161.000000  161.000000  161.000000  161.000000   
mean    51.664596   48.503106   45.776398   42.273292   52.093168   49.043478   
std     29.337677   29.097277   30.168894   28.250882   29.633132   29.139181   
min      0.000000    0.000000    0.000000    1.000000    0.000000    0.000000   
25%     27.000000   23.000000   20.000000   17.000000   29.000000   26.000000   
50%     50.000000   47.000000   49.000000   40.000000   52.000000   49.000000   
75%     80.000000   70.000000   69.000000   65.000000   79.000000   75.000000   
max     99.000000  100.000000  100.000000  100.000000  100.000000  100.000000   

            Marks  
count  161.000000  
mean   289.354037  
std     67.901161  
min    107.000000  
25%    234.000000  
50%    295.000000  
75%    331.000000  
max    441.000000

In [47]:
cp=data["C"]# in file C is cap
cp

0      97
1      77
2      69
3      72
4      95
       ..
156    87
157    58
158    61
159    26
160    94
Name: C, Length: 161, dtype: int64

In [48]:
ds=data["DS"]
ds

0      88
1      45
2       8
3      42
4      10
       ..
156    79
157    56
158    53
159    20
160     9
Name: DS, Length: 161, dtype: int64

In [49]:
ja=data["Java"]
ja

0       4
1      49
2      21
3      97
4      14
       ..
156     2
157    33
158    26
159    18
160    98
Name: Java, Length: 161, dtype: int64

In [50]:
py=data["Python"]
py

0       4
1      80
2      43
3      34
4      93
       ..
156    66
157    73
158    33
159    68
160    16
Name: Python, Length: 161, dtype: int64

In [51]:
db=data["DBMS"]
db

0      52
1       0
2      91
3      71
4      20
       ..
156    16
157    19
158    18
159    70
160    10
Name: DBMS, Length: 161, dtype: int64

In [52]:
os=data["OS"]
os

0      41
1      70
2      93
3      33
4      73
       ..
156    92
157    56
158    29
159    24
160    58
Name: OS, Length: 161, dtype: int64

In [53]:
kk=data["DS"].drop(3)
print(kk)

0      88
1      45
2       8
4      10
5      41
       ..
156    79
157    56
158    53
159    20
160     9
Name: DS, Length: 160, dtype: int64


In [54]:
data.drop("Python",axis="columns",inplace=True)
print (data)

        Roll-No                Name   C  Java  DS  OS  DBMS  Marks Grade
0    20JR1A0590            M.Sushma  97     4  88  41    52    286  Pass
1    20JR1A0591     Nagumothu Navya  77    49  45  70     0    321  Pass
2    20JR1A0592    N.Lakshmi Vasavi  69    21   8  93    91    325  Pass
3    20JR1A0593      Sushma Namburi  72    97  42  33    71    349  Pass
4    20JR1A0594  N.lakshmi Chandana  95    14  10  73    20    305  Pass
..          ...                 ...  ..   ...  ..  ..   ...    ...   ...
156  20JR1A4442               VIVEK  87     2  79  92    16    342  Pass
157  20JR1AO5J2     Charan Siva Sai  58    33  56  56    19    295  Pass
158  20jr1A0518              anusha  61    26  53  29    18    220  Pass
159  20jr1a0552                 Abc  26    18  20  24    70    226  Pass
160  20jr1ao5d8               hello  94    98   9  58    10    285  Pass

[161 rows x 9 columns]


In [55]:
data.drop("C",axis=1,inplace=True)
data

Roll-No                Name  Java  DS  OS  DBMS  Marks Grade
0    20JR1A0590            M.Sushma     4  88  41    52    286  Pass
1    20JR1A0591     Nagumothu Navya    49  45  70     0    321  Pass
2    20JR1A0592    N.Lakshmi Vasavi    21   8  93    91    325  Pass
3    20JR1A0593      Sushma Namburi    97  42  33    71    349  Pass
4    20JR1A0594  N.lakshmi Chandana    14  10  73    20    305  Pass
..          ...                 ...   ...  ..  ..   ...    ...   ...
156  20JR1A4442               VIVEK     2  79  92    16    342  Pass
157  20JR1AO5J2     Charan Siva Sai    33  56  56    19    295  Pass
158  20jr1A0518              anusha    26  53  29    18    220  Pass
159  20jr1a0552                 Abc    18  20  24    70    226  Pass
160  20jr1ao5d8               hello    98   9  58    10    285  Pass

[161 rows x 8 columns]

In [10]:
import matplotlib.pyplot as plt
#pie
#bar
#list
#plot
#scattor

In [11]:
print(dir(plt))

['Annotation', 'Arrow', 'Artist', 'AutoLocator', 'Axes', 'Button', 'Circle', 'Figure', 'FigureCanvasBase', 'FixedFormatter', 'FixedLocator', 'FormatStrFormatter', 'Formatter', 'FuncFormatter', 'GridSpec', 'IndexLocator', 'Line2D', 'LinearLocator', 'Locator', 'LogFormatter', 'LogFormatterExponent', 'LogFormatterMathtext', 'LogLocator', 'MaxNLocator', 'MultipleLocator', 'Normalize', 'NullFormatter', 'NullLocator', 'Number', 'PolarAxes', 'Polygon', 'Rectangle', 'ScalarFormatter', 'Slider', 'Subplot', 'SubplotTool', 'Text', 'TickHelper', 'Widget', '_INSTALL_FIG_OBSERVER', '_IP_REGISTERED', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_auto_draw_if_interactive', '_backend_mod', '_get_running_interactive_framework', '_interactive_bk', '_log', '_pylab_helpers', '_setp', '_setup_pyplot_info_docstrings', '_show', 'acorr', 'angle_spectrum', 'annotate', 'arrow', 'autoscale', 'autumn', 'axes', 'axhline', 'axhspan', 'axis', 'axvline', 'a

In [6]:
import numpy as np
x=np.arange(10)
y=np.arange(20,40,2)

In [12]:
plt.plot(x,y)
plt.show()